BANNED_SELECTORS = [
    ".breadcrumb",
    "#popup",
    "#flyout",
    "#site-slogan",
    "#site-name",
    "#menu",
    ".nav",
    ".login",
    ".dropdown",
    ".dropdown-menu",
    "#login",
    ".vote",
    ".form-item",
    ".user_pic_popup",
    "#post-editor",
    ".post-form",
    ".bottom-notice",
    "#sidebar",
    "#copyright",
    "#footer",
    ".footer",
    ".site-navigation",
    ".popupgroup",
    ".posthead",
    ".signaturecontainer",
    ".after_content",
    ".userinfo",
    "#similar_threads",
    ".toplinks",
    ".user-info",
    ".post-header",
    ".widget_archive",
    ".widget_categories",
    ".widget_meta",
    ".widget_recent_entries",
    ".widget_rss",
    ".wp_widget_tag_cloud",
    ".widget_calendar",
    ".navbox",
    "#mw-hidden-catlinks",
    ".above_postlist",
    "#navigation",
    ".threadtools",
    ".socialbuttons",
    "#respond",
    ".menu",
    ".WikiaHeader",
    ".buttons",
    "#WikiaRecentActivity",
    "#WikiaRandomWiki",
    ".loggedout-follow-normal",
    "#blurb",
    "#banner-top",
    ".topbar",
    ".topbar-dialog",
    ".related-links",
    ".votecell",
    ".comment-actions",
    ".d-none",
    ".Tooltip",
    ".Notices",
    ".likes-other-gravatars",
    "#logo_and_banner",
    "#pmmcrumb2",
    ".qa-notice",
    ".qa-nav-user",
    ".trackbacks",
    "#further_reading",
    ".topbar-links",
    "#your-communities-section",
    ".links-container",
    "#herobox",
    ".qa-voting-container",
    ".qa-post-when-container",
    ".qa-q-view-who",
    ".qa-q-item-meta",
    ".post-menu",
    "#vbseo-likes",
    "#side_one",
    "#side_two",
    "#feed_bar",
    ".author",
    "#likes-other-gravatars",
    ".pageInfo",
    ".ka-video-player",
    ".mw-editsection",
    ".mw-ui-icon",
    "#mw-revision-info",
    "#siteSub",
    ".heading--main",
    "#loginBarHandle",
    ".medalsrest",
    ".diff-otitle",
    ".diff-ntitle",
    ".diff-currentversion-title",
    ".diff-contentalign-left",
    '[class*="promo"]',
    '[class*="button"]',
    '[class*="upsell"]',
    ".expert-reply-overlay",
    ".PreviewContents",
    ".solutionHeader__isbn",
    ".cta",
    ".update-header",
    ".best-answer-selected",
    ".medal-info",
    "#profile-tooltip",
    ".update-info",
    ".google-search-openstudy",
    ".attachments",
    "button",
    ".delete",
    ".editor-actions",
    ".editor",
    ".files-attached",
    ".call-to-action",
    ".group-info",
    ".top-online-users",
    ".message-userExtras",
    ".message-attribution-opposite",
    ".u-srOnly",
    ".block--similarContents",
    ".u-concealed",
    ".similarThreads",
    ".breadcrumbs",
    ".courseHeader",
    ".impactSection",
    ".creativeCommons",
    "#clear",
]

BOILERPLATE_WORDS = [
    "©",
    "updates",
    "join our",
    "buy",
    "sign up",
    "no results",
    "search images",
    "all rights reserved",
    "was this",
    "please",
    "visit our",
    "download for free",
    "retrieved from",
    "home page",
    "jump to",
    "notification switch",
    "your email address",
    "view answer",
    "no label found",
    "is licensed under",
    "regular updates",
    "copyright",
    "have access to this article",
    "youtube",
    "advertisment",
    "password",
    "login",
    "learn more",
    "cookie",
    "jump to navigation",
    "download",
    "table of contents",
    "leave a reply",
    "leave a message",
    "skip to",
    "stay updated",
    "contact us",
    "twitter",
    "from wikibooks, open books for an open world",
    "last modified",
    "from wikipedia, the free encyclopedia",
    "more info",
    "terms of use",
    "terms of service",
    "privacy policy",
    "navigation",
    "sign in",
    "report error",
    "newest",
    "under license",
    "follow ",
    "newer",
    "notification",
    "post a comment",
    "click here",
    "leave a comment",
    "google",
    "free account",
    "for free",
    "alert",
    "receive update",
    "share this",
    "report ad",
    "more posts",
    "date of creation",
    "link",
    "powered by",
    "receive",
    "newsletter",
    "pdf version",
    "ask",
    "your ",
    "facebook",
    "jump to search",
    "required fields",
    "back to top",
    "published by",
    "pdf article",
    "accessload",
    "start with",
    "loading",
    "username",
    "helpful",
    "log in",
    "license",
    "get the best",
    "join us",
    "full article",
    "attribution",
    "main content",
    "printed from",
    "distributed under",
    "rss",
    "24/7",
    "your service",
    "please contact",
    "captcha",
    "might be incomplete",
    "about this",
    "lifetime",
    "access to",
    "this article is",
    "not found",
    "show more",
    "about",
    "business",
    "interested in joining",
    "wikipedia page",
    "gift",
    "premium",
    "purchase this",
    "purchasing",
    "access denied",
    "wims",
    "latest version",
    "this page",
    "your web browser",
    "recent version",
    "this article",
    "please help",
    "help you",
    "discard",
    "view tag cloud",
    "reply",
    "sponsor",
    "return to",
    "physicsoverflow is an open platform for community peer review",
    "comments",
    "trackback",
    "show menu",
    "add comment",
    "printable view",
    "advertisement",
    "join now",
    "from proofwiki",
    "energy points",
    "at the top of this image page",
    "all products",
    "maplesim",
    "online help",
    "see also",
    "all lesson plans",
    "menu",
    "check out more articles",
    "ad",
    "votes",
    "answer",
    "question you clicked on",
    "this question is closed",
]
