#!/bin/bash

set -ex

dolma -c configs/cccc/dedupe-url/CC-MAIN-2013-20.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2013-48.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2014-10.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2014-15.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2014-23.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2014-35.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2014-41.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2014-42.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2014-49.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2014-52.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2015-06.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2015-11.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2015-14.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2015-18.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2015-22.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2015-27.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2016-07.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2016-18.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2016-22.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2017-04.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2017-09.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2017-13.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2017-17.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2017-22.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2017-26.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2017-51.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2018-13.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2018-22.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2018-26.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2018-30.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2018-34.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2018-47.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2018-51.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2019-04.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2019-09.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2019-13.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2019-30.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2019-35.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2019-39.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2020-29.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2020-34.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2021-17.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2021-39.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2021-43.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2021-49.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2022-05.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2023-06.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2023-14.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2023-23.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2023-50.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2024-10.yaml dedupe
dolma -c configs/cccc/dedupe-url/CC-MAIN-2024-18.yaml dedupe